pipeline {
  agent any
  stages {
    stage("Clean Up") {
      steps {
        deleteDir()
      }
    }
    stage("Build") {
      steps {
        echo "faza build"
      }
    }
    stage("Deploy") {
      steps {
        echo "Deploy"
      }
    }
    stage("Test") {
      steps {
        echo "Test"
      }
    }
    stage("Release") {
      steps {
        echo "Release"
      }
    }
  }
}
