pipeline {
  agent any
  tools {
    maven '3.9.7'
  }
  stages {
    stage("Build") {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
    }
    stage("Test") {
      steps {
        sch 'mvn test'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }
    stage("Deliver") {
      steps {
        sh './jenkins/scripts/deliver.sh'
      }
    }
  }
}
